# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

name: $(Build.DefinitionName)-$(date:yyyyMMdd)$(rev:.r)

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    includesymbols: true
    versioningScheme: 'byBuildNumber'
- task: DotNetCoreCLI@2
  inputs:
   command: 'push'
   packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
   nuGetFeedType: 'internal'
   publishVstsFeed: '23f4464a-0072-4a37-9f45-1172e8b5bc94/70d78358-5aba-41a5-b764-ca7420f93f75'